### ISSUE TITLE
Initial Rarity Arrangement

### ISSUE THREAD

**Issue by rgharris** [rgharris/477grp3#12]
Something is wrong with the way we assign initial rarities. Several times the 6 and 8 have been found next to each other, which should not be possible.

**Comment by rgharris** [comment]
Came across this from ages ago thanks to the new Github UI so I'm closing it. I wonder if this bug was ever fixed ha. Hopefully this doesn't notify anyone :)

**Comment by kuruoujou** [comment]
Don't worry, it did! Haha.

Clearly we got it fixed. Clearly :P

**Comment by rpawling** [comment]
Uh oh. I never fixed this bug. I don't think Josh did either. It's a feature now

**Comment by jhunsber** [comment]
Yeah, I don't think we ever found root cause. :)

**Comment by kuruoujou** [comment]
Undocumented feature it is, then!
